# Change these first
owner: monetr # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: monetr
    url: https://my.monetr.app/api/health
    icon: https://my.monetr.app/favicon.ico
  - name: monetr (Staging)
    url: https://my.monetr.dev/api/health
    icon: https://my.monetr.dev/favicon.ico
  - name: Plaid
    url: https://status.plaid.com/api/v2/status.json
    __dangerous__body_degraded_if_text_missing: "All Systems Operational"

assignees:
  - elliotcourant

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.monetr.app
  # baseUrl: /status
  logoUrl: https://my.monetr.app/apple-touch-icon.png
  favicon: https://my.monetr.app/favicon.ico
  themeUrl: https://status.monetr.app/theme.css
  name: monetr Status

  introTitle: monetr's status page
  introMessage: |
    If monetr is down or undergoing maintainence you'll be able to find
    information here. You can also see [Plaid](https://plaid.com)'s general
    status here. If Plaid is having problems providing data updates then that
    may be indicated here.

  navbar:
    - title: monetr
      href: https://monetr.app
    - title: GitHub
      href: https://github.com/monetr/monetr
    - title: Discord
      href: https://discord.gg/68wTCXrhuq

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
